### ISSUE TITLE
Craft 3 bug fix

### ISSUE THREAD

**Issue by lindseydiloreto** [supercool/buttonbox#50] opened 2022-07-20 20:03 UTC
### Describe the bug

In Craft [3.7.46](https://github.com/craftcms/cms/blob/v3/CHANGELOG.md#3746---2022-06-28), a small change was made...

> `craft\fields\BaseOptionsField::translatedOptions()` now has an `$encode` argument.

Which had the unintended side effect of generating this error in Button Box...

<img width="941" alt="Ω  2022-07-20  12 54 31" src="https://user-images.githubusercontent.com/5309692/180070062-1b0b42e9-f825-42fe-8481-f24d9fdb1f43.png">

### Steps to reproduce

1. Install Craft 3.7.46 and the latest Craft 3 compatible version of Button Box.
2. Try to load any page.

### Craft CMS version

3.7.46

### Plugin version

2.0.4

### Multi-site?

No

**Comment by engram-design** [comment] 2022-07-21 02:59
Duplicate of https://github.com/verbb/buttonbox/issues/46, https://github.com/verbb/buttonbox/issues/47, https://github.com/verbb/buttonbox/issues/48 and https://github.com/verbb/buttonbox/issues/49 (please search 😉)

Already fixed in [3.1.0](https://github.com/verbb/buttonbox/releases/tag/3.1.0)

Please run `composer require verbb/buttonbox && composer remove supercool/buttonbox` to remove the old package and install the new one. Otherwise, you'll be stuck on [2.0.2](https://github.com/verbb/buttonbox/releases/tag/2.0.2) (the last version available for the `supercool/buttonbox` package.

**Closed as completed by engram-design** 2022-07-21 02:59 UTC

**Comment by lindseydiloreto** [comment] 2022-07-21 18:38
Ah, my bad! I thought I had searched, but apparently I didn't search very well.

I didn't even realize there was a 3.x version, not sure why I was stuck on 2.x. Switching to the latest 3.x version completely fixed the problem. 👍 

Thanks man, sorry for clogging your Github feed! 😄
