### ISSUE TITLE
PHP Warning after Upgrade to Craft CMS 3.7.47

### ISSUE THREAD

**Issue by thomasbendl** [supercool/buttonbox#48] opened 2022-07-06 10:28 UTC
PHP Warning – yii\base\ErrorException

Declaration of verbb\buttonbox\fields\Buttons::translatedOptions(): array should be compatible with craft\fields\BaseOptionsField::translatedOptions(bool $encode = false): array
1. in /home/bogencb6/www.bogensberger.com/vendor/verbb/buttonbox/src/fields/Buttons.php at line 200
191192193194195196197198199200201202203204205206207208209        foreach ($options as $option) {
            if (!empty($option['default'])) {
                return $option['value'];
            }
        }
 
        return $options[0]['value'];
    }
 
    protected function translatedOptions(): array
    {
        $translatedOptions = [];
 
        foreach ($this->options as $option) {
            $translatedOptions[] = [
                'label' => Craft::t('site', $option['label']),
                'value' => $option['value'],
                'showLabel' => $option['showLabel'],
                'imageUrl' => $option['imageUrl'],

### Steps to reproduce

1. Upgrade from craft 3.7.44 -> 3.4.47
2. 

### Craft CMS version

3.7.47

### Plugin version

3.0.2

### Multi-site?

No

### Additional context

happend on production!

**Comment by engram-design** [comment] 2022-07-06 10:30
Duplicate of https://github.com/verbb/buttonbox/issues/47 please update to [3.1.0](https://github.com/verbb/buttonbox/releases/tag/3.1.0)

**Closed as completed by engram-design** 2022-07-06 10:30 UTC
